version: '3'
services:
  app:
    build: .
    command: tail -f /dev/null
    volumes:
      - .:/app
      - ~/.config/gcloud:/root/.config/gcloud
    environment:
      DATABASE_ID: ''
      DATABASE_USER: 'postgres'
      DATABASE_PASSWORD: 'postgres'
      DATABASE_NAME: 'postgres'
      DATABASE_HOST: 'db'
      DATABASE_PORT: 5432
      FLASK_ENV: development
      HOST: 0.0.0.0
    ports:
    - 5000:5000

  db:
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
